USE CLEANER;

SHOW TABLES;

SELECT * FROM PAGO;
SELECT * FROM PAGO ORDER BY ID_TRANSACCION DESC; 
SELECT DISTINCT FORMA_PAGO FROM PAGO;

SELECT * FROM CLIENTE;

DESCRIBE PAGO;



INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 5000, 'ak-std-000036');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 100, 'ak-std-000037');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 300, 'ak-std-000038');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 4075, 'ak-std-000039');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'cheque', SYSDATE(), 6035, 'ak-std-000040');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 198459, 'ak-std-000041');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 22000, 'ak-std-000042');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 150, 'ak-std-000043');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 34578, 'ak-std-000044');

INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (4,'paypal', SYSDATE(), 73, 'ak-std-000045');

DELIMITER //
CREATE PROCEDURE SP_INSERTAR_PAGOS (IN P_codigo_cliente INT, IN p_forma_pago VARCHAR(40),
IN p_id_transaccion VARCHAR (50), IN p_fecha_pago DATE,IN P_total INT)

BEGIN
   INSERT INTO PAGO (CODIGO_CLIENTE, FORMA_PAGO, FECHA_PAGO, TOTAL, ID_TRANSACCION)
VALUES (p_codigo_cliente, p_forma_pago, p_fecha_pago, p_total, p_id_transaccion);

END //
DELIMITER // ;


 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),5000,'ak-std-000036');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),100,'ak-std-000037');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),300,'ak-std-000038');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),4073,'ak-std-000039');
 CALL SP_INSERTAR_PAGOS (4, 'cheque',SYSDATE(),6035,'ak-std-000040');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),193459,'ak-std-000041');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),22000,'ak-std-000042');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),150,'ak-std-000043');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),34578,'ak-std-000044');
 CALL SP_INSERTAR_PAGOS (4, 'paypal',SYSDATE(),73,'ak-std-000045');


CREATE TABLE AUDITORIA (ID INT AUTO_INCREMENT PRIMARY KEY,
MENSAJE VARCHAR (100),
FECHA TIMESTAMP DEFAULT current_timestamp);
DROP EVENT LOG_AUTOMATICO
CREATE EVENT LOG_AUTOMATICO
ON SCHEDULE EVERY  1 minute
DO
    INSERT INTO AUDITORIA(MENSAJE)
    VALUES ('Mensaje guardado automaticamente');
    
    SHOW VARIABLES LIKE 'event_scheduler';
    
    SET GLOBAL event_scheduler = ON;
    
    SHOW EVENTS;
    
    SELECT * FROM AUDITORIA;
    
CREATE PROCEDURE SP_INSERTAR_AUDITORIA ( IN p_MENSAJE VARCHAR (100)

BEGIN
 INSERT INTO AUDITORIA (id, MENSAJE,FECHA)
 VALUES (p_id,p_mensaje,p_fecha);
 
 END 
 
 DELIMITER //
 
 CREATE EVENT LOG_AUDITORIA
 ON SCHEDULE EVERY 1 minute
 DO
 CALL SP_INSERTAR_AUDITORIA ('QUE MÁS KEVIN')
 